import "./globals.css";
import type { Metadata } from "next";
import Banner from "./_components/Banner";
import Header from "./_components/Header";

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    <html lang="en">
      <body className="mx-auto max-w-7xl bg-zinc-100 dark:bg-zinc-800">
        <Header />
        <Banner />
        {children}
      </body>
    </html>
  );
}
